name: bricoloni_v2
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_spinbox: ^0.13.1
  image_picker: ^1.0.1
  flutter_form_builder: any
  latlong2: any
  geocoding: ^2.1.0
  http: any
  google_maps_flutter: ^2.2.3
  google_fonts : ^4.0.4
  stripe_checkout: ^1.0.1
  pay: ^1.1.0
  jwt_decoder: ^2.0.1
  flutter_bloc: ^8.1.3
  provider: ^6.0.5
  web_socket_channel: ^2.4.0
  geolocator: ^8.2.0
  flutter_map: any
  jwt_decode: ^0.3.1
  path_provider: any
  pdf: any
  url_launcher: any
  image: ^3.0.2
  stripe_sdk: any
  flutter_charts: ^0.5.1
  fl_chart: ^0.63.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets :
    - lib/images/
    - assets/classifier.tflite
    - lib/images/construct.jpg
    - C:/Users/ridha/AndroidStudioProjects/bricolini/Front/lib/images/construct.jpg

